### ISSUE TITLE
AHRS_WiFi.ino fails to compile due to #else if

### ISSUE THREAD

**Issue by jantje** [i3water/blinker-library#1]
When testing Sloeber I found the AHRS_WiFi.ino example not to compile.
The root cause is a mistake in the define here:
https://github.com/i3water/blinker-library/blob/a62770fdfd56049ab80da355d13d320b908b0753/src/utility/BlinkerDebug.h#L25
removing the `if `solved the issue

**Comment by i3water** [comment]
Thanks ! I will fix this bug.
