### ISSUE TITLE
Question - No description of what Blinker does.  What is it for?

### ISSUE THREAD

**Issue by RudyFiero** [i3water/blinker-library#2]
You have a lot of good documentation here but there is not description of what Blinker does. Yes it has a joystick, slider, or button input. But what does that do? What is it for?

**Comment by i3water** [comment]
Thanks,

Blinker is a smartphone app.Blinker-library is a library for arduino to communicate with Blinker.You can use button/joystick/slider/ahrs to control your arduino, arduino can send back message to display on phone.

More information https://github.com/blinker-iot/blinker-doc/wiki ,
we will perfect app/library/wiki as soon as prossible.
